version: "3.4"

services:
  app:
    image: svelte-christmas-tree
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: ["sh", "-c", "npm install; npm run dev"]
    volumes:
      - .:/app:cached
    ports:
      - 5000:5000
      - 35729:35729 # Hot Reload用
